import Link from "next/link";
import Image from "next/image";
import { CmsImage } from "@/components/ui/CmsImage";
import { Section, SectionHeader } from "@/components/ui/Section";
import { Reveal } from "@/components/ui/Reveal";
import { FlowThreads } from "@/components/ui/FlowThreads";
import { Button } from "@/components/ui/Button";
import { ArrowRight } from "lucide-react";
import { getInsights } from "@/lib/content";
import { MobileAutoSlider } from "@/components/ui/MobileAutoSlider";
import { Accordion } from "@/components/ui/Accordion";

export const metadata = {
  title: "Insights",
  description: "Perspectives on GCC strategy, talent, location, and engagement models.",
};

export const dynamic = "force-dynamic";

export default async function InsightsPage() {
  const insights = await getInsights();

  const featuredInsights = insights.filter((i: { featured?: boolean }) => i.featured === true);
  const regularInsights = insights.filter((i: { featured?: boolean }) => i.featured !== true);

  const displayFeatured =
    featuredInsights.length > 0 ? featuredInsights : insights.length > 0 ? [insights[0]] : [];
  const displayRegular =
    featuredInsights.length > 0 ? regularInsights : insights.slice(1);

  const assessmentFaqs = [
    {
      id: "faq-duration",
      title: "How long does the assessment take?",
      content:
        "The questionnaire itself takes about 10 minutes to complete. Because every output is reviewed and validated by our in-house GCC experts, not just generated and served instantly, your full report is delivered within 2 business days.",
    },
    {
      id: "faq-free",
      title: "Is it free?",
      content:
        "Yes, free, with no obligation. Nobody contacts you unless you ask to speak with an advisor.",
    },
    {
      id: "faq-confidential",
      title: "Will my information be kept confidential?",
      content:
        "Yes. Everything you share stays strictly confidential. We do not use your information for marketing and we do not sell it to any third party. It is used solely to build your assessment and, if you choose, to inform a conversation with a Vertara advisor.",
    },
    {
      id: "faq-preparer",
      title: "Who prepares the output?",
      content:
        "Your report is generated by Vertara’s proprietary AI-enabled assessment engine, our in-house model built on the same feasibility framework our founders have applied across ten GCC builds, and every output is reviewed and validated by our in-house GCC experts before it reaches you.",
    },
    {
      id: "faq-advice",
      title: "Is the output professional advice?",
      content:
        "No. It is a preliminary, expert-validated view generated from your own answers, an input to a conversation with us, not a substitute for legal, tax or financial advice.",
    },
    {
      id: "faq-next-steps",
      title: "What happens after I receive it?",
      content:
        "You can keep the report, or hand it straight to a Vertara advisor as the starting point for a Discover-stage conversation, so the first call starts with a validated point of view, not a blank page.",
    },
  ];

  return (
    <div className="w-full font-sans" style={{ fontFamily: 'Calibri' }}>
      {/* 1. HERO SECTION */}
      <section className="relative overflow-hidden text-white bg-[#2F3F34]">
        <div className="relative mx-auto max-w-6xl px-4 py-16 sm:px-6 md:py-20 lg:py-24 lg:px-8">
          {/* Breadcrumb / Eyebrow */}
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
            <span>Knowledge</span>
            <span>/</span>
            <span>Perspectives</span>
          </div>

          <h1 className="mt-4 max-w-2xl text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl lg:text-[44px] xl:text-[48px] leading-tight text-white">
            Insights
          </h1>

          <p className="mt-4 max-w-xl text-base text-white/90 sm:text-lg leading-relaxed font-normal">
            Practical thinking on building and running capability centres in India, from people who've done it. Read our Nano GCC intelligence, Infrastructure Studies; GCC Strategy white papers and Short Guides on the decisions that matter most: where to build, how big to start and which operating model fits.
          </p>
        </div>
      </section>

      {/* 2. WHAT LIVES HERE SECTION (3 CARDS PER ROW, LIGHT GREEN BG, WHITE CARDS WITH GOLD ACCENTS) */}
      <section
        id="what-lives-here"
        className="w-full bg-[#edf5ef] pt-12 sm:pt-14 md:pt-16 pb-4 sm:pb-6 font-sans"
        style={{ fontFamily: 'Calibri' }}
      >
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          {/* Eyebrow & Header */}
          <div className="mb-8 sm:mb-12">
            <p className="text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
              WHAT LIVES HERE
            </p>
            <h2 className="mt-3 text-2xl sm:text-3xl md:text-4xl font-bold tracking-tight text-[#101C30]">
              Vertara’s perspective on building GCCs
            </h2>

          </div>

          {/* Cards: Auto & Manual Slider on mobile (no arrows, dots only), 3-column Grid on desktop */}
          <MobileAutoSlider
            autoSlideInterval={3500}
            desktopClassName="md:grid md:grid-cols-2 lg:grid-cols-3 md:gap-6 lg:gap-7"
            itemClassName="w-[85vw] max-w-[340px] shrink-0 snap-center md:w-auto md:max-w-none flex flex-col h-full"
            dotTone="gold"
          >
            {/* Card 01 */}
            <div
              id="card-assessment"
              className="flex flex-col justify-between rounded-2xl border border-[#cddcd1] border-t-4 border-t-[#B59439] bg-white p-6 sm:p-7 shadow-xs transition-all duration-300 hover:-translate-y-1 hover:shadow-md hover:border-[#B59439]/50 scroll-mt-24 h-full"
            >
              <div>
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold uppercase tracking-wider text-[#B59439]">
                    Tools & Expertise
                  </span>
                  <span className="text-sm font-bold text-[#B59439] font-mono">01</span>
                </div>
                <h3 className="mt-3 text-lg sm:text-xl font-bold text-[#101C30] leading-snug">
                  Run Your GCC Assessment
                </h3>
                <p className="mt-3 text-sm leading-relaxed text-[#101C30]/75">
                  A free feasibility assessment, delivered within 2 business days.
                </p>
              </div>
            </div>

            {/* Card 02 */}
            <div
              id="card-market-research"
              className="flex flex-col justify-between rounded-2xl border border-[#cddcd1] border-t-4 border-t-[#B59439] bg-white p-6 sm:p-7 shadow-xs transition-all duration-300 hover:-translate-y-1 hover:shadow-md hover:border-[#B59439]/50 scroll-mt-24 h-full"
            >
              <div>
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold uppercase tracking-wider text-[#B59439]">
                    Tools & Expertise
                  </span>
                  <span className="text-sm font-bold text-[#B59439] font-mono">02</span>
                </div>
                <h3 className="mt-3 text-lg sm:text-xl font-bold text-[#101C30] leading-snug">
                  Market Research
                </h3>
                <p className="mt-3 text-sm leading-relaxed text-[#101C30]/75">
                  A standing, expert-delivered service.
                </p>
              </div>
            </div>

            {/* Card 03 */}
            <div
              id="card-workplace-strategy"
              className="flex flex-col justify-between rounded-2xl border border-[#cddcd1] border-t-4 border-t-[#B59439] bg-white p-6 sm:p-7 shadow-xs transition-all duration-300 hover:-translate-y-1 hover:shadow-md hover:border-[#B59439]/50 scroll-mt-24 h-full"
            >
              <div>
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold uppercase tracking-wider text-[#B59439]">
                    Tools & Expertise
                  </span>
                  <span className="text-sm font-bold text-[#B59439] font-mono">03</span>
                </div>
                <h3 className="mt-3 text-lg sm:text-xl font-bold text-[#101C30] leading-snug">
                  Workplace Strategy & Change Management
                </h3>
                <p className="mt-3 text-sm leading-relaxed text-[#101C30]/75">
                  A standing, expert-delivered service.
                </p>
              </div>
            </div>

            {/* Card 04 */}
            <div
              id="card-nano-gcc-series"
              className="flex flex-col justify-between rounded-2xl border border-[#cddcd1] border-t-4 border-t-[#B59439] bg-white p-6 sm:p-7 shadow-xs transition-all duration-300 hover:-translate-y-1 hover:shadow-md hover:border-[#B59439]/50 scroll-mt-24 h-full"
            >
              <div>
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold uppercase tracking-wider text-[#B59439]">
                    Research
                  </span>
                  <span className="text-sm font-bold text-[#B59439] font-mono">04</span>
                </div>
                <h3 className="mt-3 text-lg sm:text-xl font-bold text-[#101C30] leading-snug">
                  Nano GCC series
                </h3>

              </div>
            </div>

            {/* Card 05 */}
            <div
              id="white-papers"
              className="flex flex-col justify-between rounded-2xl border border-[#cddcd1] border-t-4 border-t-[#B59439] bg-white p-6 sm:p-7 shadow-xs transition-all duration-300 hover:-translate-y-1 hover:shadow-md hover:border-[#B59439]/50 scroll-mt-24 h-full"
            >
              <div>
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold uppercase tracking-wider text-[#B59439]">
                    Research & Perspective
                  </span>
                  <span className="text-sm font-bold text-[#B59439] font-mono">05</span>
                </div>
                <h3 className="mt-3 text-lg sm:text-xl font-bold text-[#101C30] leading-snug">
                  White papers
                </h3>
                <p className="mt-3 text-sm leading-relaxed text-[#101C30]/75">
                  Longer research pieces, starting with the Japan–India GCC corridor paper.
                </p>
              </div>
            </div>

            {/* Card 06 */}
            <div
              id="linkedin-digest"
              className="flex flex-col justify-between rounded-2xl border border-[#cddcd1] border-t-4 border-t-[#B59439] bg-white p-6 sm:p-7 shadow-xs transition-all duration-300 hover:-translate-y-1 hover:shadow-md hover:border-[#B59439]/50 scroll-mt-24 h-full"
            >
              <div>
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold uppercase tracking-wider text-[#B59439]">
                    Research & Perspective
                  </span>
                  <span className="text-sm font-bold text-[#B59439] font-mono">06</span>
                </div>
                <h3 className="mt-3 text-lg sm:text-xl font-bold text-[#101C30] leading-snug">
                  LinkedIn digest
                </h3>
                <p className="mt-3 text-sm leading-relaxed text-[#101C30]/75">
                  A rolling roundup of the weekly and monthly LinkedIn updates, kept on-site so they don’t disappear into a feed.
                </p>
              </div>
            </div>
          </MobileAutoSlider>
        </div>
      </section>

      {/* 3. RUN YOUR GCC ASSESSMENT SECTION */}
      <section
        id="assessment"
        className="relative overflow-hidden w-full bg-[#F5F2EA] py-14 sm:py-16 md:py-20 border-b border-[#D8D2C0] font-sans scroll-mt-20"
        style={{ fontFamily: 'Calibri' }}
      >
        <div className="relative mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-14 items-center">
            {/* Left Content Column */}
            <div className="lg:col-span-7">
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
                  FREE FEASIBILITY ASSESSMENT
                </span>
              </div>

              <h2 className="mt-3 text-2xl sm:text-3xl md:text-4xl lg:text-[38px] font-bold tracking-tight text-[#101C30] leading-tight">
                Run Your GCC Assessment
              </h2>

              {/* <p className="mt-4 text-base sm:text-lg text-[#101C30] font-semibold leading-relaxed">
                A free feasibility assessment at the top of the Insights page the natural first click for a visitor who isn’t ready to talk yet but wants a real, expert-validated answer to should we even do this.
              </p> */}

              <p className="mt-3 text-sm sm:text-base leading-relaxed text-[#101C30]/85 font-normal italic" style={{ fontFamily: 'Calibri' }}>
                See whether a GCC or a Nano GCC is the right move. Answer a short set of questions about your business about 10 minutes. Our proprietary, AI-enabled assessment engine builds your feasibility report, and our in-house GCC experts personally review and validate every output before it’s delivered to you within 2 business days.
              </p>



              <div className="mt-6 sm:mt-7">
                <Button
                  href="/contact?intent=assessment"
                  size="lg"
                  className="font-bold text-sm sm:text-base px-8 py-3.5 bg-[#2F3F34] hover:bg-[#2F3F34] text-white rounded-xl shadow-none hover:shadow-none inline-flex items-center transition-none"
                >
                  Request Your GCC Assessment <ArrowRight className="ml-2 h-4 w-4 text-white" />
                </Button>
              </div>
            </div>

            {/* Right Value Breakdown (Uncarded, Simple Dots) */}
            <div className="lg:col-span-5 lg:pl-4">
              <div className="space-y-4">
                <div className="pb-2">
                  <p className="text-xs font-bold uppercase tracking-wider text-[#B59439]">
                    What you receive
                  </p>
                  <p className="text-lg sm:text-xl font-bold text-[#101C30] mt-1">
                    Confidential Feasibility Report
                  </p>
                </div>

                <ul className="space-y-3.5 text-sm sm:text-base text-[#101C30]">
                  <li className="flex items-start gap-3">
                    <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                    <div>
                      <p className="font-bold text-[#101C30]">10 Minutes</p>
                      <p className="text-xs sm:text-sm text-[#101C30]/75">Short, structured questions about your business mandate.</p>
                    </div>
                  </li>

                  <li className="flex items-start gap-3">
                    <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                    <div>
                      <p className="font-bold text-[#101C30]">AI Engine + Expert Validated</p>
                      <p className="text-xs sm:text-sm text-[#101C30]/75">Proprietary modeling personally validated by GCC practitioners.</p>
                    </div>
                  </li>

                  <li className="flex items-start gap-3">
                    <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                    <div>
                      <p className="font-bold text-[#101C30]">Delivered in 2 Business Days</p>
                      <p className="text-xs sm:text-sm text-[#101C30]/75">Delivered directly to your inbox with a clear point of view.</p>
                    </div>
                  </li>

                  <li className="flex items-start gap-3">
                    <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                    <div>
                      <p className="font-bold text-[#101C30]">Strictly Confidential</p>
                      <p className="text-xs sm:text-sm text-[#101C30]/75">Never used for marketing or sold to any third party.</p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          {/* Subsection: What the assessment covers */}
          <div className="mt-10 sm:mt-12">
            <div className="mb-6 sm:mb-8">
              <span className="text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
                Scope of Analysis
              </span>
              <h3 className="mt-2 text-xl sm:text-2xl md:text-[26px] font-bold text-[#101C30] tracking-tight">
                What the assessment covers
              </h3>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-5 lg:gap-x-14">
              {/* Left Column (4 points) */}
              <div className="space-y-4 sm:space-y-5">
                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Strategic intent</strong> — Why now, and what outcome the centre needs to deliver cost, capability, or both.
                  </p>
                </div>

                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Work portability</strong> — Which functions can genuinely move, and which depend on judgment that has to stay close to HQ.
                  </p>
                </div>

                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Nano GCC fit</strong> — Whether a lean 20–100 person pilot is the right way to prove the model before committing to full scale.
                  </p>
                </div>

                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Talent & location</strong> — India talent depth for your specific role mix tier-1 and tier-2 cities weighed equally.
                  </p>
                </div>
              </div>

              {/* Right Column (4 points) */}
              <div className="space-y-4 sm:space-y-5">
                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Governance & operating model</strong> — Captive, build-operate-transfer, managed centre or hybrid scored against your control and speed needs.
                  </p>
                </div>

                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Cost & funding</strong> — A realistic multi-year cost picture and where the breakeven point actually falls.
                  </p>
                </div>

                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Risk & compliance</strong> — Entity structure, data obligations and the compliance load a lean centre can actually carry.
                  </p>
                </div>

                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Change readiness</strong> — Leadership bandwidth and HQ buy in the two things that stall a GCC as often as the business case does.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Subsection: What you get back */}
          <div className="mt-10 sm:mt-12">
            <div className="mb-6 sm:mb-8">
              <span className="text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
                Deliverables
              </span>
              <h3 className="mt-2 text-xl sm:text-2xl md:text-[26px] font-bold text-[#101C30] tracking-tight">
                What you get back
              </h3>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-5">
              {/* Row 1 - Card 1 */}
              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">A scored feasibility view</strong> across all eight dimensions
                </p>
              </div>

              {/* Row 1 - Card 2 */}
              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">A recommended path</strong> Nano GCC pilot, mid-scale build, or not yet.
                </p>
              </div>

              {/* Row 2 - Card 3 */}
              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">Operating-model options</strong> ranked against your stated priorities
                </p>
              </div>

              {/* Row 2 - Card 4 */}
              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">A short India location shortlist</strong>, tier-1 and tier-2
                </p>
              </div>
            </div>
          </div>

          {/* Subsection: Assessment FAQ */}
          <div className="mt-10 sm:mt-12">
            <div className="mb-6 sm:mb-8">
              <span className="text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
                FAQ
              </span>
              <h3 className="mt-2 text-xl sm:text-2xl md:text-[26px] font-bold text-[#101C30] tracking-tight">
                Assessment FAQ
              </h3>
            </div>

            <Accordion
              items={assessmentFaqs}
              className="border-[#D8D2C0] divide-[#e2e8f0] bg-white shadow-xs"
            />
          </div>
        </div>
      </section>

      {/* 4. CTA BANNER (What should your GCC look like?) */}
      <section
        id="cta-mandate"
        className="relative w-full overflow-hidden bg-[#B59439] py-12 sm:py-14 md:py-16 text-[#101C30] font-sans border-t border-b border-[#a6862f]"
        style={{ fontFamily: 'Calibri' }}
      >
        <div className="relative z-[1] mx-auto w-full max-w-5xl px-4 sm:px-6 lg:px-8 text-center">
          <Reveal>
            <div>
              <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold tracking-tight text-[#101C30] leading-tight">
                See whether a GCC is the right move.
              </h2>

              <p className="mt-3 sm:mt-4 text-base sm:text-lg leading-relaxed text-[#101C30]/90 max-w-3xl mx-auto">
                Get an expert validated feasibility view of your GCC opportunity including whether to start with a Nano GCC, build at mid-scale, or wait.
              </p>

              <div className="mt-7 sm:mt-8 flex flex-col sm:flex-row items-center justify-center gap-4 sm:gap-5">
                <Link
                  href="/contact?intent=assessment"
                  className="w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-xl bg-[#2F3F34] px-7 py-3.5 text-base sm:text-lg font-bold text-white shadow-md transition-all duration-200 hover:bg-[#233027] hover:shadow-lg hover:-translate-y-0.5"
                >
                  <span>Request Your GCC Assessment</span>
                  <ArrowRight className="h-5 w-5" />
                </Link>

                <Link
                  href="/contact"
                  className="w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-xl border-2 border-[#2F3F34] bg-transparent px-7 py-3.5 text-base sm:text-lg font-bold text-[#2F3F34] transition-all duration-200 hover:bg-[#2F3F34] hover:text-white hover:shadow-md hover:-translate-y-0.5"
                >
                  <span>Discuss Your GCC Mandate</span>
                  <ArrowRight className="h-5 w-5" />
                </Link>
              </div>
            </div>
          </Reveal>
        </div>
      </section>

      {/* 5. MARKET RESEARCH SECTION (2nd Insight / Commissioned Service) */}
      <section
        id="market-research"
        className="relative overflow-hidden w-full font-sans scroll-mt-20"
        style={{ fontFamily: 'Calibri' }}
      >
        {/* Top Block: Header & Cards with cream background */}
        <div className="w-full bg-[#F5F2EA] py-14 sm:py-16 md:py-20 border-b border-[#D8D2C0]">
          <div className="relative mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
            {/* Header Block */}
            <div className="w-full">
              <span className="text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
                COMMISSIONED SERVICE · STANDALONE ADVISORY
              </span>

              <h2 className="mt-3 text-2xl sm:text-3xl md:text-4xl lg:text-[38px] font-bold tracking-tight text-[#101C30] leading-tight">
                Market Research — Firsthand knowledge, not an AI output
              </h2>

              <p className="mt-5 text-base sm:text-lg text-[#101C30]/90 leading-relaxed font-normal w-full">
                Alongside our published point of view, Vertara offers Market Research as a standalone, commissioned service for companies who want an expert, India specific view before they commit to a GCC mandate. This is deliberately not an AI-generated report, it is firsthand knowledge, delivered directly by Vertara’s own GCC operators and sector specialists the same people who have personally led ten GCC builds not a synthesized or automated output. Where the Assessment tool gives you a fast, AI-enabled first read, Market Research gives you the judgment of someone who has actually made the call before.
              </p>
            </div>

            {/* 4 Scope Deliverables / Focus Areas (2 rows of 2 cards) */}
            <div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-5">
              {/* Card 1 */}
              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">Location and cost benchmarking</strong> — tier-1 and tier-2 cities, sized to your actual role mix, not a generic ranking.
                </p>
              </div>

              {/* Card 2 */}
              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">Competitive and peer-GCC intelligence</strong> — who’s building what, where, and why, across your sector.
                </p>
              </div>

              {/* Card 3 */}
              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">Sector-specific talent market mapping</strong> — depth, cost and availability by discipline.
                </p>
              </div>

              {/* Card 4 */}
              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">Custom feasibility and market-entry research</strong> — delivered as a standalone engagement, or folded into the Discover stage of a build.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Bottom Block: Positioning & Commercial Principles in white */}
        <div className="w-full bg-white py-12 sm:py-14 md:py-16 border-b border-[#e2e8f0]">
          <div className="relative mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
              <div className="lg:col-span-7">
                <p className="text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
                  Positioning
                </p>
                <p className="mt-3 text-base sm:text-lg text-[#101C30] leading-relaxed font-normal">
                  Insightful, expert-led research not a generic market report, and not an AI output. Every engagement is delivered firsthand by practitioners who’ve made these calls themselves, for companies that need a defensible answer before they commit capital.
                </p>
              </div>

              <div className="lg:col-span-5 rounded-2xl bg-[#edf5ef] border border-[#cddcd1] p-6 sm:p-7">
                <p className="text-xs font-bold uppercase tracking-wider text-[#2F3F34]">
                  Commercial Principles
                </p>
                <p className="mt-2.5 text-sm sm:text-base text-[#101C30]/85 leading-relaxed">
                  Commercially, Market Research engagements typically run as an <strong>Advisory Retainer</strong> or a scoped <strong>Project-Based</strong> engagement — see the{" "}
                  <Link
                    href="/offerings"
                    className="font-bold text-[#2F3F34] underline decoration-[#B59439] decoration-2 underline-offset-4 hover:text-[#B59439] transition-colors"
                  >
                    Commercial Principles on Our Offerings →
                  </Link>
                </p>

                <div className="mt-5">
                  <Button
                    href="/contact?intent=market-research"
                    size="md"
                    className="w-full sm:w-auto font-bold text-sm bg-[#2F3F34] hover:bg-[#233027] text-white rounded-xl shadow-none inline-flex items-center justify-center"
                  >
                    Discuss Market Research <ArrowRight className="ml-2 h-4 w-4 text-white" />
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 6. WORKPLACE STRATEGY & CHANGE MANAGEMENT SECTION (3rd Insight / Standing Service) */}
      <section
        id="workplace-strategy"
        className="relative overflow-hidden w-full font-sans scroll-mt-20"
        style={{ fontFamily: 'Calibri' }}
      >
        {/* Top Block: Header & Cards with cream background */}
        <div className="w-full bg-[#F5F2EA] py-14 sm:py-16 md:py-20 border-b border-[#D8D2C0]">
          <div className="relative mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
            {/* Header Block */}
            <div className="w-full">
              <span className="text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
                TOOLS & EXPERTISE · STANDING SERVICE
              </span>

              <h2 className="mt-3 text-2xl sm:text-3xl md:text-4xl lg:text-[38px] font-bold tracking-tight text-[#101C30] leading-tight">
                Workplace Strategy & Change Management
              </h2>

              <p className="mt-5 text-base sm:text-lg text-[#101C30]/90 leading-relaxed font-normal w-full">
                Standing up a GCC changes how an organization works, not just where the work happens. Vertara’s Workplace Strategy & Change Management service covers the physical and human side of that transition workspace and real estate strategy alongside a structured change program, so the centre doesn’t just launch, it sticks. We run change using the ADKAR framework Awareness, Desire, Knowledge, Ability, Reinforcement the same discipline behind every stage of the Vertara build model.
              </p>
            </div>

            {/* 5 Focus Areas / Deliverables */}
            <div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-5">
              {/* Card 1 - Full Width */}
              <div className="md:col-span-2 flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">Workspace and real estate strategy</strong> — custom-designed or managed offices, sized to the centre’s actual stage, not over-built for a headcount you don’t have yet.
                </p>
              </div>

              {/* Card 2 - Awareness */}
              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">Awareness</strong> — building the case for change with HQ stakeholders and the new centre’s first hires, so the “why” lands before the “what.”
                </p>
              </div>

              {/* Card 3 - Desire */}
              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">Desire</strong> — securing genuine buy-in from the people the change affects, not just sign-off from the people funding it.
                </p>
              </div>

              {/* Card 4 - Knowledge & Ability */}
              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">Knowledge & Ability</strong> — structured onboarding, training and capability-building so the new team can actually do the job, not just show up for it.
                </p>
              </div>

              {/* Card 5 - Reinforcement */}
              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">Reinforcement</strong> — governance and feedback loops that make the change stick past the first 90 days, instead of reverting once the launch excitement fades.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Bottom Block: Positioning & Commercial Principles in white */}
        <div className="w-full bg-white py-12 sm:py-14 md:py-16 border-b border-[#e2e8f0]">
          <div className="relative mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
              <div className="lg:col-span-7">
                <p className="text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
                  Positioning
                </p>
                <p className="mt-3 text-base sm:text-lg text-[#101C30] leading-relaxed font-normal">
                  Change management for a GCC isn’t a slide deck it’s the difference between a centre that runs the way it was designed to and one that quietly reverts to old habits within a year.
                </p>
              </div>

              <div className="lg:col-span-5 rounded-2xl bg-[#edf5ef] border border-[#cddcd1] p-6 sm:p-7">
                <p className="text-xs font-bold uppercase tracking-wider text-[#2F3F34]">
                  Commercial Principles
                </p>
                <p className="mt-2.5 text-sm sm:text-base text-[#101C30]/85 leading-relaxed">
                  Commercially, Workplace Strategy & Change Management typically runs as a <strong>Project-Based / Managed Workstream</strong>, or is folded into the Design and Build stages of a full engagement — see the{" "}
                  <Link
                    href="/offerings"
                    className="font-bold text-[#2F3F34] underline decoration-[#B59439] decoration-2 underline-offset-4 hover:text-[#B59439] transition-colors"
                  >
                    Commercial Principles on Our Offerings →
                  </Link>
                </p>

                <div className="mt-5">
                  <Button
                    href="/contact?intent=workplace-strategy"
                    size="md"
                    className="w-full sm:w-auto font-bold text-sm bg-[#2F3F34] hover:bg-[#233027] text-white rounded-xl shadow-none inline-flex items-center justify-center"
                  >
                    Discuss Workplace Strategy <ArrowRight className="ml-2 h-4 w-4 text-white" />
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 7. INSIGHTS ARTICLES SECTION / NANO GCC SERIES */}
      <Section id="nano-gcc-series" className="scroll-mt-20">
        {/* Section Header: Nano GCC Series */}
        <div className="mb-8 sm:mb-12">
          <span className="text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
            Research
          </span>
          <h2 className="mt-2 text-2xl sm:text-3xl md:text-4xl font-bold tracking-tight text-[#101C30]">
            Nano GCC Series
          </h2>

        </div>

        {/* FEATURED INSIGHT (HERO CARD) */}
        {displayFeatured.length > 0 && (
          <div className="space-y-12">
            {displayFeatured.map((insight: {
              slug: string;
              title: string;
              excerpt: string;
              coverImage?: string;
              category: string;
            }) => (
              <Reveal key={insight.slug}>
                <article
                  className="relative overflow-hidden rounded-3xl border border-[#B59439]/30 bg-gradient-to-br from-[#14233c] via-[#101C30] to-[#0b1424] text-white shadow-2xl shadow-[#101C30]/30 p-6 sm:p-8 md:p-10 lg:p-12"
                  style={{ fontFamily: 'Calibri' }}
                >
                  {/* Foreground Content */}
                  <div className="relative z-10 max-w-3xl">
                    {/* Featured Pill Badge */}
                    <div className="flex items-center gap-3">
                      <span className="inline-flex items-center rounded-full bg-[#B59439] px-4 py-1.5 text-xs font-bold uppercase tracking-wider text-white shadow-sm">
                        Featured Paper
                      </span>
                    </div>

                    {/* Category Eyebrow */}
                    <p className="mt-4 text-xs font-bold uppercase tracking-[0.2em] text-[#B59439] sm:text-sm">
                      {insight.category || "TALENT"}
                    </p>

                    {/* Title */}
                    <h3 className="mt-3 text-2xl font-bold tracking-tight text-white sm:text-3xl md:text-4xl lg:text-[40px] leading-tight">
                      <Link href={`/insights/${insight.slug}`} className="hover:text-[#B59439] transition-colors">
                        {insight.title}
                      </Link>
                    </h3>

                    {/* Excerpt */}
                    <p className="mt-4 text-base sm:text-lg leading-relaxed text-white/85 font-normal max-w-2xl">
                      {insight.excerpt}
                    </p>

                    {/* Read CTA */}
                    <div className="mt-7 sm:mt-8">
                      <Button href={`/insights/${insight.slug}`} variant="gold" size="lg" className="font-bold shadow-md">
                        Read full article <ArrowRight className="ml-1 h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                </article>
              </Reveal>
            ))}
          </div>
        )}

        {/* REMAINING INSIGHTS (RESPONSIVE CARD GRID) */}
        {displayRegular.length > 0 && (
          <div className="mt-10">
            <div className="grid grid-cols-1 gap-6 sm:gap-8 md:grid-cols-2 lg:grid-cols-3">
              {displayRegular.map((insight: {
                slug: string;
                title: string;
                excerpt: string;
                coverImage?: string;
                category: string;
              }) => (
                <Reveal key={insight.slug}>
                  <article className="group flex h-full flex-col overflow-hidden rounded-2xl border border-[#cddcd1] bg-surface-elevated transition hover:-translate-y-1 hover:border-[#2F3F34]/40 hover:bg-[#edf5ef]/30 hover:shadow-lg">
                    {/* Card Top Image */}
                    <Link href={`/insights/${insight.slug}`} className="block">
                      <div className="relative h-48 w-full overflow-hidden bg-surface sm:h-52">
                        <CmsImage
                          src={insight.coverImage?.trim() || "/images/gcc-ops.png"}
                          alt={insight.title || "Insight cover"}
                          fill
                          className="object-cover transition duration-500 group-hover:scale-105"
                          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                        />
                        <div className="absolute left-3 top-3 z-10">
                          <span className="inline-flex items-center rounded-full border border-white/10 bg-[#0b1f3a]/85 px-2.5 py-0.5 text-[11px] font-semibold uppercase tracking-wider text-white shadow-sm backdrop-blur-sm">
                            {insight.category}
                          </span>
                        </div>
                      </div>
                    </Link>

                    {/* Card Body */}
                    <div className="flex flex-1 flex-col p-5 sm:p-6">
                      <h3 className="text-lg font-bold leading-snug text-navy transition-colors group-hover:text-accent">
                        <Link href={`/insights/${insight.slug}`} className="hover:underline">
                          {insight.title}
                        </Link>
                      </h3>

                      <p className="mt-3 flex-1 text-sm leading-relaxed text-muted line-clamp-3">
                        {insight.excerpt}
                      </p>

                      <div className="mt-5 pt-4 border-t border-[#cddcd1]/60 flex items-center justify-between">
                        <Link
                          href={`/insights/${insight.slug}`}
                          className="inline-flex items-center gap-1.5 text-xs sm:text-sm font-semibold text-accent transition hover:text-accent-hover"
                        >
                          Read article
                          <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5" />
                        </Link>
                      </div>
                    </div>
                  </article>
                </Reveal>
              ))}
            </div>
          </div>
        )}
      </Section>
    </div>
  );
}
