import Link from "next/link";
import { Accordion } from "@/components/ui/Accordion";
import { ArrowRight } from "lucide-react";

const assessmentFaqs = [
  {
    id: "faq-duration",
    title: "How long does the assessment take?",
    content:
      "The questionnaire itself takes about 10 minutes to complete. Because every output is reviewed and validated by our in-house GCC experts, not just generated and served instantly, your full report is delivered within 2 business days.",
  },
  {
    id: "faq-free",
    title: "Is it free?",
    content:
      "Yes, free, with no obligation. Nobody contacts you unless you ask to speak with an advisor.",
  },
  {
    id: "faq-confidential",
    title: "Will my information be kept confidential?",
    content:
      "Yes. Everything you share stays strictly confidential. We do not use your information for marketing and we do not sell it to any third party. It is used solely to build your assessment and, if you choose, to inform a conversation with a Vertara advisor.",
  },
  {
    id: "faq-preparer",
    title: "Who prepares the output?",
    content:
      "Your report is generated by Vertara’s proprietary AI-enabled assessment engine, our in-house model built on the same feasibility framework our founders have applied across ten GCC builds, and every output is reviewed and validated by our in-house GCC experts before it reaches you.",
  },
  {
    id: "faq-advice",
    title: "Is the output professional advice?",
    content:
      "No. It is a preliminary, expert-validated view generated from your own answers, an input to a conversation with us, not a substitute for legal, tax or financial advice.",
  },
  {
    id: "faq-next-steps",
    title: "What happens after I receive it?",
    content:
      "You can keep the report, or hand it straight to a Vertara advisor as the starting point for a Discover-stage conversation, so the first call starts with a validated point of view, not a blank page.",
  },
];

export function FreeFeasibilityAssessmentSection() {
  return (
    <>
      <section
        id="assessment"
        className="relative overflow-hidden w-full bg-[#F5F2EA] py-14 sm:py-16 md:py-20 border-b border-[#D8D2C0] font-sans scroll-mt-20"
        style={{ fontFamily: "Calibri" }}
      >
        <div className="relative mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          {/* Subsection: What the assessment covers */}
          <div>
            <div className="mb-6 sm:mb-8">
              <span className="text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
                Scope of Analysis
              </span>
              <h3 className="mt-2 text-xl sm:text-2xl md:text-[26px] font-bold text-[#101C30] tracking-tight">
                What the GCC assessment covers
              </h3>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-5 lg:gap-x-14">
              {/* Left Column (4 points) */}
              <div className="space-y-4 sm:space-y-5">
                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Strategic intent</strong> — Why now, and what outcome the centre needs to deliver cost, capability, or both.
                  </p>
                </div>

                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Work portability</strong> — Which functions can genuinely move, and which depend on judgment that has to stay close to HQ.
                  </p>
                </div>

                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Nano GCC fit</strong> — Whether a lean 20–100 person pilot is the right way to prove the model before committing to full scale.
                  </p>
                </div>

                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Talent & location</strong> — India talent depth for your specific role mix tier-1 and tier-2 cities weighed equally.
                  </p>
                </div>
              </div>

              {/* Right Column (4 points) */}
              <div className="space-y-4 sm:space-y-5">
                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Governance & operating model</strong> — Captive, build-operate-transfer, managed centre or hybrid scored against your control and speed needs.
                  </p>
                </div>

                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Cost & funding</strong> — A realistic multi-year cost picture and where the breakeven point actually falls.
                  </p>
                </div>

                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Risk & compliance</strong> — Entity structure, data obligations and the compliance load a lean centre can actually carry.
                  </p>
                </div>

                <div className="flex items-start gap-3">
                  <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                  <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                    <strong className="font-bold text-[#101C30]">Change readiness</strong> — Leadership bandwidth and HQ buy in the two things that stall a GCC as often as the business case does.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Subsection: What you get back */}
          <div className="mt-10 sm:mt-12">
            <div className="mb-6 sm:mb-8">
              <span className="text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
                Deliverables
              </span>
              <h3 className="mt-2 text-xl sm:text-2xl md:text-[26px] font-bold text-[#101C30] tracking-tight">
                What you get back
              </h3>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-5">
              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">A scored feasibility view</strong> across all eight dimensions
                </p>
              </div>

              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">A recommended path</strong> Nano GCC pilot, mid-scale build, or not yet.
                </p>
              </div>

              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">Operating-model options</strong> ranked against your stated priorities
                </p>
              </div>

              <div className="flex items-start gap-3.5 rounded-xl border border-[#D8D2C0] bg-white p-5 sm:p-6 shadow-xs">
                <span className="h-2 w-2 rounded-full bg-[#B59439] shrink-0 mt-2" />
                <p className="text-sm sm:text-base text-[#101C30] leading-relaxed">
                  <strong className="font-bold text-[#101C30]">A short India location shortlist</strong>, tier-1 and tier-2
                </p>
              </div>
            </div>
          </div>

          {/* Subsection: Assessment FAQ */}
          <div className="mt-10 sm:mt-12">
            <div className="mb-6 sm:mb-8">
              <span className="text-xs font-bold uppercase tracking-[0.2em] text-[#B59439]">
                Frequently Asked Questions
              </span>
              <h3 className="mt-2 text-xl sm:text-2xl md:text-[26px] font-bold text-[#101C30] tracking-tight">
                Questions we often hear before the first call
              </h3>
            </div>

            <Accordion
              items={assessmentFaqs}
              className="border-[#D8D2C0] divide-[#e2e8f0] bg-white shadow-xs"
            />
          </div>
        </div>
      </section>

      {/* CTA BANNER: See whether a GCC is the right move */}
      <section
        id="cta-assessment"
        className="relative w-full overflow-hidden bg-[#B59439] py-12 sm:py-14 md:py-16 text-[#101C30] font-sans border-t border-b border-[#a6862f]"
        style={{ fontFamily: "Calibri" }}
      >
        <div className="relative z-[1] mx-auto w-full max-w-5xl px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold tracking-tight text-[#101C30] leading-tight">
            See whether a GCC is the right move.
          </h2>

          <p className="mt-3 sm:mt-4 text-base sm:text-lg leading-relaxed text-[#101C30]/90 max-w-3xl mx-auto">
            Get an expert validated feasibility view of your GCC opportunity including whether to start with a Nano GCC, build at mid-scale, or wait.
          </p>

          <div className="mt-7 sm:mt-8 flex items-center justify-center">
            <Link
              href="/assessment"
              className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#2F3F34] px-7 py-3.5 text-base sm:text-lg font-bold text-white shadow-md transition-all duration-200 hover:bg-[#233027] hover:shadow-lg hover:-translate-y-0.5 cursor-pointer"
            >
              <span>Request Your GCC Assessment</span>
              <ArrowRight className="h-5 w-5 text-white" />
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}
